### ISSUE TITLE
On Ubuntu build i get:

### ISSUE THREAD

**Issue by wbonis** [gl-inet/lede-17.01#1]
gli-net/lede-17.01# make
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] package/cleanup
 make[2] package/compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/libnl-tiny compile
 make[3] -C package/libs/libjson-c compile
 make[3] -C package/utils/lua compile
 make[3] -C package/libs/libubox compile
 make[3] -C package/system/ubus compile
 make[3] -C package/system/uci compile
 make[3] -C package/network/config/netifd compile
 make[3] -C package/system/ubox compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/libs/ncurses compile
 make[3] -C package/utils/util-linux compile
 make[3] -C package/libs/lzo compile
 make[3] -C package/libs/zlib compile
 make[3] -C package/utils/mtd-utils compile
 make[3] -C package/system/fstools compile
 make[3] -C package/system/fwtool host-compile
 make[3] -C package/system/fwtool compile
 make[3] -C package/system/procd compile
 make[3] -C package/system/usign host-compile
 make[3] -C package/utils/jsonfilter compile
 make[3] -C package/system/lede-keyring compile
 make[3] -C package/system/usign compile
 make[3] -C package/base-files compile
 make[3] -C package/boot/uboot-envtools compile
 make[3] -C package/libs/openssl compile
 make[3] -C feeds/gli_pub/lighttpd compile
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
/opt/xxx/src/gli-net/lede-17.01/include/toplevel.mk:198: recipe for target 'world' failed

The Error is the dependency to libpcre:

configure: error: pcre-config not found, install the pcre-devel package or build with --without-pcre
Makefile:151: recipe for target '/opt/xxx/src/gli-net/lede-17.01/build_dir/target-mips_24kc_musl-1.1.16/lighttpd-1.4.37/.configured_yyyyyyyy' failed

Can this be fixed?

**Comment by kysonlok** [comment]
Maybe you can issue "sudo apt-get install libpcre3-dev" install libpcre on your host machine, and then rebuild it with "make package/feeds/gli_pub/lighttpd/{clean,compile} V=s".

**Comment by kysonlok** [comment]
@ZimboBoyd
